from pathlib import Path
from setuptools import setup

setup(name='pipp', 
	version='0.0',
	description="A python script to postprocess the Path Integral MD trajctory generated by LAMMPS",
	packages=["pipp"],
    scripts=[str(p) for p in Path("bin").iterdir()],
	zip_safe=True)
